server:
  hostname: 'HOSTNAME'
  port: 'PORT'
  adminPort: 'ADMIN_PORT'

authentication:
  username: 'USER'
  password: 'PASSWD'

database:
  connectString: 'DBURL'
  user: 'DBUSER'
  password: 'DBPASSWD'
